server:
  port: 8081
  servlet:
   context-path: /bootcamp
   
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-18-214-195-34.compute-1.amazonaws.com:5432/db0ttjqemh3q5d
    username: sugpchjajrjeyy
    password: 536da89f00d490c7964e53a222fa7bf365d948d54aa1daaf9460d5e54ca03c1a
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-dll: true
    hibernate:
      dll-auto: none
    
    
application:  
  description: Projeto criado para o BOOTCAMO DIO - Santander
