server:
  port: 8081
  servlet:
   context-path: /bootcamp
   
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://vaxrpzxixznduc:42f969666a1b60849441236f60b55236ebacec76c4f5e05b2aed0e7705d2773f@ec2-34-193-101-0.compute-1.amazonaws.com:5432/d9rolmukgc02b2
    username: vaxrpzxixznduc
    password: 42f969666a1b60849441236f60b55236ebacec76c4f5e05b2aed0e7705d2773f
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-dll: true
    hibernate:
      dll-auto: none
    
    
application:  
  description: Projeto criado para o BOOTCAMO DIO - Santander
