server:
  port: 8081
  servlet:
   context-path: /bootcamp
   
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JBDC_DATASOURCE_URL}
jpa:
  show-sql: true
  database-plataform: org.hibernate.dialect.PostgreSQLDialect
  generate-dll: true
  hibernate:
    dll-auto: none
    
    
application:  
  description: Projeto criado para o BOOTCAMO DIO - Santander
